"""Create approved Stage 1 schema

Revision ID: 43f8329127b0
Revises:
Create Date: 2026-08-06 13:26:11.140110

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = "43f8329127b0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "materials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.Unicode(length=50), nullable=False),
        sa.Column("name", sa.Unicode(length=200), nullable=False),
        sa.Column("unit", sa.Unicode(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_materials")),
        sa.UniqueConstraint("code", name=op.f("uq_materials_code")),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.Unicode(length=50), nullable=False),
        sa.Column("name", sa.Unicode(length=200), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("code", name=op.f("uq_products_code")),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.Unicode(length=30), nullable=False),
        sa.Column("name", sa.Unicode(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("code", name=op.f("uq_roles_code")),
    )
    op.create_table(
        "stations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.Unicode(length=30), nullable=False),
        sa.Column("name", sa.Unicode(length=100), nullable=False),
        sa.Column("printer_name", sa.Unicode(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stations")),
        sa.UniqueConstraint("code", name=op.f("uq_stations_code")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.Unicode(length=50), nullable=False),
        sa.Column("password_hash", sa.Unicode(length=255), nullable=False),
        sa.Column("display_name", sa.Unicode(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at_utc", sa.DateTime().with_variant(mssql.DATETIME2(), "mssql"), nullable=False
        ),
        sa.Column(
            "updated_at_utc", sa.DateTime().with_variant(mssql.DATETIME2(), "mssql"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("event_type", sa.Unicode(length=50), nullable=False),
        sa.Column("entity_type", sa.Unicode(length=50), nullable=False),
        sa.Column("entity_id", sa.Unicode(length=100), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("station_id", sa.Integer(), nullable=True),
        sa.Column(
            "occurred_at_utc",
            sa.DateTime().with_variant(mssql.DATETIME2(), "mssql"),
            nullable=False,
        ),
        sa.Column(
            "detail", sa.UnicodeText().with_variant(mssql.NVARCHAR(None), "mssql"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["station_id"], ["stations.id"], name=op.f("fk_audit_logs_station_id_stations")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_audit_logs_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_table(
        "formulas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.Unicode(length=50), nullable=False),
        sa.Column("name", sa.Unicode(length=200), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_formulas_product_id_products")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_formulas")),
        sa.UniqueConstraint("code", name=op.f("uq_formulas_code")),
    )
    op.create_table(
        "raw_material_lots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.Integer(), nullable=False),
        sa.Column("lot_no", sa.Unicode(length=100), nullable=False),
        sa.Column("qc_status", sa.Unicode(length=20), nullable=False),
        sa.Column("expiry_date", sa.Date().with_variant(mssql.DATE(), "mssql"), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "qc_status IN ('PASS', 'HOLD', 'REJECT')", name=op.f("ck_raw_material_lots_qc_status")
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_raw_material_lots_material_id_materials"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_material_lots")),
        sa.UniqueConstraint("material_id", "lot_no", name=op.f("uq_raw_material_lots_material_id")),
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_user_roles_role_id_roles")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_roles_user_id_users")
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id", name=op.f("pk_user_roles")),
    )
    op.create_table(
        "formula_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("formula_id", sa.Integer(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.Integer(), nullable=False),
        sa.Column("target_weight", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("unit", sa.Unicode(length=20), nullable=False),
        sa.CheckConstraint(
            "target_weight > 0", name=op.f("ck_formula_items_target_weight_positive")
        ),
        sa.ForeignKeyConstraint(
            ["formula_id"], ["formulas.id"], name=op.f("fk_formula_items_formula_id_formulas")
        ),
        sa.ForeignKeyConstraint(
            ["material_id"], ["materials.id"], name=op.f("fk_formula_items_material_id_materials")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_formula_items")),
        sa.UniqueConstraint("formula_id", "line_no", name=op.f("uq_formula_items_formula_id")),
    )
    op.create_table(
        "production_orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("po_no", sa.Unicode(length=50), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("production_lot", sa.Unicode(length=100), nullable=False),
        sa.Column("formula_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.Unicode(length=20), nullable=False),
        sa.Column("prepared_by_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "prepared_at_utc", sa.DateTime().with_variant(mssql.DATETIME2(), "mssql"), nullable=True
        ),
        sa.CheckConstraint(
            "status IN ('OPEN', 'READY', 'COMPLETED', 'CANCELLED')",
            name=op.f("ck_production_orders_status"),
        ),
        sa.ForeignKeyConstraint(
            ["formula_id"], ["formulas.id"], name=op.f("fk_production_orders_formula_id_formulas")
        ),
        sa.ForeignKeyConstraint(
            ["prepared_by_user_id"],
            ["users.id"],
            name=op.f("fk_production_orders_prepared_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_production_orders_product_id_products")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_production_orders")),
        sa.UniqueConstraint("po_no", name=op.f("uq_production_orders_po_no")),
    )
    op.create_table(
        "weighing_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("preweight_id", sa.Unicode(length=40), nullable=False),
        sa.Column("production_order_id", sa.Integer(), nullable=False),
        sa.Column("formula_item_id", sa.Integer(), nullable=False),
        sa.Column("raw_material_lot_id", sa.Integer(), nullable=False),
        sa.Column("target_weight_snapshot", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("actual_weight", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("unit_snapshot", sa.Unicode(length=20), nullable=False),
        sa.Column("station_id", sa.Integer(), nullable=False),
        sa.Column("weighed_by_user_id", sa.Integer(), nullable=False),
        sa.Column(
            "weighed_at_utc", sa.DateTime().with_variant(mssql.DATETIME2(), "mssql"), nullable=False
        ),
        sa.Column("status", sa.Unicode(length=20), nullable=False),
        sa.Column("consumed_by_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "consumed_at_utc", sa.DateTime().with_variant(mssql.DATETIME2(), "mssql"), nullable=True
        ),
        sa.Column("voided_by_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "voided_at_utc", sa.DateTime().with_variant(mssql.DATETIME2(), "mssql"), nullable=True
        ),
        sa.Column("void_reason", sa.Unicode(length=500), nullable=True),
        sa.CheckConstraint(
            "status IN ('COMPLETED', 'CONSUMED', 'VOIDED')",
            name=op.f("ck_weighing_transactions_status"),
        ),
        sa.CheckConstraint(
            "actual_weight > 0", name=op.f("ck_weighing_transactions_actual_weight_positive")
        ),
        sa.ForeignKeyConstraint(
            ["consumed_by_user_id"],
            ["users.id"],
            name=op.f("fk_weighing_transactions_consumed_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["formula_item_id"],
            ["formula_items.id"],
            name=op.f("fk_weighing_transactions_formula_item_id_formula_items"),
        ),
        sa.ForeignKeyConstraint(
            ["production_order_id"],
            ["production_orders.id"],
            name=op.f("fk_weighing_transactions_production_order_id_production_orders"),
        ),
        sa.ForeignKeyConstraint(
            ["raw_material_lot_id"],
            ["raw_material_lots.id"],
            name=op.f("fk_weighing_transactions_raw_material_lot_id_raw_material_lots"),
        ),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["stations.id"],
            name=op.f("fk_weighing_transactions_station_id_stations"),
        ),
        sa.ForeignKeyConstraint(
            ["voided_by_user_id"],
            ["users.id"],
            name=op.f("fk_weighing_transactions_voided_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["weighed_by_user_id"],
            ["users.id"],
            name=op.f("fk_weighing_transactions_weighed_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_weighing_transactions")),
        sa.UniqueConstraint("preweight_id", name=op.f("uq_weighing_transactions_preweight_id")),
    )
    with op.batch_alter_table("weighing_transactions", schema=None) as batch_op:
        batch_op.create_index(
            "uq_weighing_active_formula_line",
            ["production_order_id", "formula_item_id"],
            unique=True,
            mssql_where=sa.text("status IN ('COMPLETED', 'CONSUMED')"),
            sqlite_where=sa.text("status IN ('COMPLETED', 'CONSUMED')"),
        )

    op.create_table(
        "label_print_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("weighing_transaction_id", sa.Integer(), nullable=False),
        sa.Column("print_type", sa.Unicode(length=20), nullable=False),
        sa.Column("result", sa.Unicode(length=20), nullable=False),
        sa.Column("printer_name", sa.Unicode(length=255), nullable=True),
        sa.Column("printed_by_user_id", sa.Integer(), nullable=False),
        sa.Column(
            "printed_at_utc", sa.DateTime().with_variant(mssql.DATETIME2(), "mssql"), nullable=False
        ),
        sa.Column("reason", sa.Unicode(length=500), nullable=True),
        sa.Column("error_message", sa.Unicode(length=1000), nullable=True),
        sa.CheckConstraint(
            "print_type IN ('ORIGINAL', 'RETRY', 'REPRINT')",
            name=op.f("ck_label_print_logs_print_type"),
        ),
        sa.CheckConstraint(
            "result IN ('SUCCESS', 'FAILED')", name=op.f("ck_label_print_logs_result")
        ),
        sa.ForeignKeyConstraint(
            ["printed_by_user_id"],
            ["users.id"],
            name=op.f("fk_label_print_logs_printed_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["weighing_transaction_id"],
            ["weighing_transactions.id"],
            name=op.f("fk_label_print_logs_weighing_transaction_id_weighing_transactions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_label_print_logs")),
    )
    op.create_table(
        "verification_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("expected_production_order_id", sa.Integer(), nullable=True),
        sa.Column("scanned_preweight_id", sa.Unicode(length=40), nullable=False),
        sa.Column("weighing_transaction_id", sa.Integer(), nullable=True),
        sa.Column("result", sa.Unicode(length=10), nullable=False),
        sa.Column("reason_code", sa.Unicode(length=50), nullable=True),
        sa.Column("detail", sa.Unicode(length=500), nullable=True),
        sa.Column("verified_by_user_id", sa.Integer(), nullable=False),
        sa.Column(
            "verified_at_utc",
            sa.DateTime().with_variant(mssql.DATETIME2(), "mssql"),
            nullable=False,
        ),
        sa.CheckConstraint("result IN ('PASS', 'FAIL')", name=op.f("ck_verification_logs_result")),
        sa.ForeignKeyConstraint(
            ["expected_production_order_id"],
            ["production_orders.id"],
            name=op.f("fk_verification_logs_expected_production_order_id_production_orders"),
        ),
        sa.ForeignKeyConstraint(
            ["verified_by_user_id"],
            ["users.id"],
            name=op.f("fk_verification_logs_verified_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["weighing_transaction_id"],
            ["weighing_transactions.id"],
            name=op.f("fk_verification_logs_weighing_transaction_id_weighing_transactions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verification_logs")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("verification_logs")
    op.drop_table("label_print_logs")
    with op.batch_alter_table("weighing_transactions", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_weighing_active_formula_line",
            mssql_where=sa.text("status IN ('COMPLETED', 'CONSUMED')"),
            sqlite_where=sa.text("status IN ('COMPLETED', 'CONSUMED')"),
        )

    op.drop_table("weighing_transactions")
    op.drop_table("production_orders")
    op.drop_table("formula_items")
    op.drop_table("user_roles")
    op.drop_table("raw_material_lots")
    op.drop_table("formulas")
    op.drop_table("audit_logs")
    op.drop_table("users")
    op.drop_table("stations")
    op.drop_table("roles")
    op.drop_table("products")
    op.drop_table("materials")
