"""Add material tag issuance foundation.

Downgrade is destructive after issued records exist and requires separate approval.

Revision ID: b0551011c146
Revises: c8d4e6f1a2b3
Create Date: 2026-08-18 14:20:10.449055

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = "b0551011c146"
down_revision = "c8d4e6f1a2b3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "material_import_batches",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("original_filename", sa.Unicode(length=255), nullable=False),
        sa.Column("file_sha256", sa.Unicode(length=64), nullable=False),
        sa.Column("status", sa.Unicode(length=20), nullable=False),
        sa.Column("total_rows", sa.Integer(), nullable=False),
        sa.Column("inserted_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("updated_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("unchanged_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("rejected_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("uploaded_by_user_id", sa.Integer(), nullable=False),
        sa.Column(
            "uploaded_at_utc",
            sa.DateTime().with_variant(mssql.DATETIME2(), "mssql"),
            nullable=False,
        ),
        sa.Column("applied_by_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "applied_at_utc", sa.DateTime().with_variant(mssql.DATETIME2(), "mssql"), nullable=True
        ),
        sa.Column("idempotency_key", sa.Unicode(length=36), nullable=False),
        sa.Column("error_summary", sa.Unicode(length=1000), nullable=True),
        sa.CheckConstraint(
            "status IN ('PREVIEWED', 'APPLIED', 'FAILED', 'EXPIRED')",
            name=op.f("ck_material_import_batches_status"),
        ),
        sa.ForeignKeyConstraint(
            ["applied_by_user_id"],
            ["users.id"],
            name=op.f("fk_material_import_batches_applied_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_user_id"],
            ["users.id"],
            name=op.f("fk_material_import_batches_uploaded_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_material_import_batches")),
        sa.UniqueConstraint(
            "idempotency_key", name=op.f("uq_material_import_batches_idempotency_key")
        ),
    )
    with op.batch_alter_table("material_import_batches", schema=None) as batch_op:
        batch_op.create_index(
            "ix_material_import_batches_file_sha256", ["file_sha256"], unique=False
        )

    op.create_table(
        "material_import_rows",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "import_batch_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("item_code_normalized", sa.Unicode(length=50), nullable=True),
        sa.Column("category_no_normalized", sa.Unicode(length=30), nullable=True),
        sa.Column("name_normalized", sa.Unicode(length=200), nullable=True),
        sa.Column("result", sa.Unicode(length=20), nullable=False),
        sa.Column("reason_code", sa.Unicode(length=50), nullable=True),
        sa.Column("reason_detail", sa.Unicode(length=500), nullable=True),
        sa.CheckConstraint(
            "result IN ('INSERT', 'UPDATE', 'UNCHANGED', 'REJECTED')",
            name=op.f("ck_material_import_rows_result"),
        ),
        sa.ForeignKeyConstraint(
            ["import_batch_id"],
            ["material_import_batches.id"],
            name=op.f("fk_material_import_rows_import_batch_id_material_import_batches"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_material_import_rows")),
        sa.UniqueConstraint(
            "import_batch_id", "row_number", name=op.f("uq_material_import_rows_import_batch_id")
        ),
    )
    op.create_table(
        "material_tag_batches",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("batch_no", sa.Unicode(length=40), nullable=False),
        sa.Column("material_id", sa.Integer(), nullable=False),
        sa.Column("material_code_snapshot", sa.Unicode(length=50), nullable=False),
        sa.Column("material_name_snapshot", sa.Unicode(length=200), nullable=False),
        sa.Column("unit_snapshot", sa.Unicode(length=20), nullable=False),
        sa.Column("category_no_snapshot", sa.Unicode(length=30), nullable=True),
        sa.Column("receiving_date", sa.Date().with_variant(sa.DATE(), "mssql"), nullable=False),
        sa.Column("expiry_date", sa.Date().with_variant(sa.DATE(), "mssql"), nullable=False),
        sa.Column("purchase_order", sa.Unicode(length=100), nullable=False),
        sa.Column("purchase_order_line", sa.Unicode(length=30), nullable=False),
        sa.Column("delivery_invoice", sa.Unicode(length=100), nullable=False),
        sa.Column("vendor_lot", sa.Unicode(length=100), nullable=False),
        sa.Column("supplier", sa.Unicode(length=100), nullable=False),
        sa.Column("comment", sa.Unicode(length=200), server_default=sa.text("''"), nullable=False),
        sa.Column("warehouse", sa.Unicode(length=50), nullable=False),
        sa.Column("location", sa.Unicode(length=50), nullable=False),
        sa.Column("shelf", sa.Unicode(length=50), nullable=False),
        sa.Column("total_received_weight", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("standard_container_weight", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("tag_count", sa.Integer(), nullable=False),
        sa.Column(
            "qr_payload", sa.UnicodeText().with_variant(sa.NVARCHAR(), "mssql"), nullable=False
        ),
        sa.Column("issued_by_user_id", sa.Integer(), nullable=False),
        sa.Column(
            "issued_at_utc", sa.DateTime().with_variant(mssql.DATETIME2(), "mssql"), nullable=False
        ),
        sa.Column("source_draft_token", sa.Unicode(length=36), nullable=False),
        sa.CheckConstraint(
            "expiry_date >= receiving_date",
            name=op.f("ck_material_tag_batches_expiry_not_before_receiving"),
        ),
        sa.CheckConstraint(
            "standard_container_weight > 0",
            name=op.f("ck_material_tag_batches_standard_container_weight_positive"),
        ),
        sa.CheckConstraint(
            "tag_count BETWEEN 1 AND 200", name=op.f("ck_material_tag_batches_tag_count_range")
        ),
        sa.CheckConstraint(
            "total_received_weight > 0",
            name=op.f("ck_material_tag_batches_total_received_weight_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["issued_by_user_id"],
            ["users.id"],
            name=op.f("fk_material_tag_batches_issued_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_material_tag_batches_material_id_materials"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_material_tag_batches")),
        sa.UniqueConstraint("batch_no", name=op.f("uq_material_tag_batches_batch_no")),
        sa.UniqueConstraint(
            "source_draft_token", name=op.f("uq_material_tag_batches_source_draft_token")
        ),
    )
    with op.batch_alter_table("material_tag_batches", schema=None) as batch_op:
        batch_op.create_index(
            "ix_material_tag_batches_code_vendor_lot",
            ["material_code_snapshot", "vendor_lot"],
            unique=False,
        )
        batch_op.create_index(
            "ix_material_tag_batches_delivery_invoice", ["delivery_invoice"], unique=False
        )
        batch_op.create_index(
            "ix_material_tag_batches_issued_by", ["issued_by_user_id"], unique=False
        )
        batch_op.create_index(
            "ix_material_tag_batches_material_receiving",
            ["material_id", "receiving_date"],
            unique=False,
        )
        batch_op.create_index(
            "ix_material_tag_batches_purchase_order", ["purchase_order"], unique=False
        )

    op.create_table(
        "material_tag_drafts",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("draft_token", sa.Unicode(length=36), nullable=False),
        sa.Column("idempotency_key", sa.Unicode(length=36), nullable=False),
        sa.Column("material_id", sa.Integer(), nullable=False),
        sa.Column("receiving_date", sa.Date().with_variant(sa.DATE(), "mssql"), nullable=False),
        sa.Column("purchase_order", sa.Unicode(length=100), nullable=False),
        sa.Column("purchase_order_line", sa.Unicode(length=30), nullable=False),
        sa.Column("material_code", sa.Unicode(length=50), nullable=False),
        sa.Column("delivery_invoice", sa.Unicode(length=100), nullable=False),
        sa.Column("vendor_lot", sa.Unicode(length=100), nullable=False),
        sa.Column("supplier", sa.Unicode(length=100), nullable=False),
        sa.Column("comment", sa.Unicode(length=200), server_default=sa.text("''"), nullable=False),
        sa.Column("warehouse", sa.Unicode(length=50), nullable=False),
        sa.Column("location", sa.Unicode(length=50), nullable=False),
        sa.Column("shelf", sa.Unicode(length=50), nullable=False),
        sa.Column("total_received_weight", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("standard_container_weight", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("calculated_tag_count", sa.Integer(), nullable=False),
        sa.Column(
            "calculated_weights_json",
            sa.UnicodeText().with_variant(sa.NVARCHAR(), "mssql"),
            nullable=False,
        ),
        sa.Column("status", sa.Unicode(length=20), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at_utc", sa.DateTime().with_variant(mssql.DATETIME2(), "mssql"), nullable=False
        ),
        sa.Column(
            "expires_at_utc", sa.DateTime().with_variant(mssql.DATETIME2(), "mssql"), nullable=False
        ),
        sa.Column(
            "issued_batch_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.CheckConstraint(
            "status IN ('PREVIEWED', 'ISSUED', 'EXPIRED')",
            name=op.f("ck_material_tag_drafts_status"),
        ),
        sa.CheckConstraint(
            "calculated_tag_count BETWEEN 1 AND 200",
            name=op.f("ck_material_tag_drafts_calculated_tag_count_range"),
        ),
        sa.CheckConstraint(
            "standard_container_weight > 0",
            name=op.f("ck_material_tag_drafts_standard_container_weight_positive"),
        ),
        sa.CheckConstraint(
            "total_received_weight > 0",
            name=op.f("ck_material_tag_drafts_total_received_weight_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_material_tag_drafts_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["issued_batch_id"],
            ["material_tag_batches.id"],
            name=op.f("fk_material_tag_drafts_issued_batch_id_material_tag_batches"),
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_material_tag_drafts_material_id_materials"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_material_tag_drafts")),
        sa.UniqueConstraint("draft_token", name=op.f("uq_material_tag_drafts_draft_token")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_material_tag_drafts_idempotency_key")),
    )
    op.create_table(
        "material_tags",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("batch_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("sequence_no", sa.Integer(), nullable=False),
        sa.Column("container_weight", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column(
            "created_at_utc", sa.DateTime().with_variant(mssql.DATETIME2(), "mssql"), nullable=False
        ),
        sa.CheckConstraint(
            "container_weight > 0", name=op.f("ck_material_tags_container_weight_positive")
        ),
        sa.CheckConstraint("sequence_no > 0", name=op.f("ck_material_tags_sequence_no_positive")),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["material_tag_batches.id"],
            name=op.f("fk_material_tags_batch_id_material_tag_batches"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_material_tags")),
        sa.UniqueConstraint("batch_id", "sequence_no", name=op.f("uq_material_tags_batch_id")),
    )
    op.create_table(
        "material_tag_print_events",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("batch_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "material_tag_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True
        ),
        sa.Column("print_scope", sa.Unicode(length=20), nullable=False),
        sa.Column("print_type", sa.Unicode(length=20), nullable=False),
        sa.Column("result", sa.Unicode(length=20), nullable=False),
        sa.Column("reason", sa.Unicode(length=500), nullable=True),
        sa.Column("requested_by_user_id", sa.Integer(), nullable=False),
        sa.Column(
            "requested_at_utc",
            sa.DateTime().with_variant(mssql.DATETIME2(), "mssql"),
            nullable=False,
        ),
        sa.Column("printer_name", sa.Unicode(length=255), nullable=True),
        sa.Column("error_message", sa.Unicode(length=1000), nullable=True),
        sa.CheckConstraint(
            "print_scope IN ('BATCH', 'INDIVIDUAL')",
            name=op.f("ck_material_tag_print_events_print_scope"),
        ),
        sa.CheckConstraint(
            "print_type IN ('ORIGINAL', 'REPRINT')",
            name=op.f("ck_material_tag_print_events_print_type"),
        ),
        sa.CheckConstraint(
            "result IN ('RENDERED', 'FAILED')", name=op.f("ck_material_tag_print_events_result")
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["material_tag_batches.id"],
            name=op.f("fk_material_tag_print_events_batch_id_material_tag_batches"),
        ),
        sa.ForeignKeyConstraint(
            ["material_tag_id"],
            ["material_tags.id"],
            name=op.f("fk_material_tag_print_events_material_tag_id_material_tags"),
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"],
            ["users.id"],
            name=op.f("fk_material_tag_print_events_requested_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_material_tag_print_events")),
    )
    with op.batch_alter_table("material_tag_print_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_material_tag_print_events_batch", ["batch_id", "requested_at_utc"], unique=False
        )
        batch_op.create_index(
            "ix_material_tag_print_events_requester",
            ["requested_by_user_id", "requested_at_utc"],
            unique=False,
        )
        batch_op.create_index(
            "ix_material_tag_print_events_tag",
            ["material_tag_id", "requested_at_utc"],
            unique=False,
        )

    with op.batch_alter_table("materials", schema=None) as batch_op:
        batch_op.add_column(sa.Column("source_category_no", sa.Unicode(length=30), nullable=True))
        batch_op.add_column(
            sa.Column(
                "updated_at_utc",
                sa.DateTime().with_variant(mssql.DATETIME2(), "mssql"),
                nullable=True,
            )
        )
        batch_op.add_column(sa.Column("updated_by_user_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_materials_updated_by_user_id_users"),
            "users",
            ["updated_by_user_id"],
            ["id"],
        )
        batch_op.create_index("ix_materials_name", ["name"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("materials", schema=None) as batch_op:
        batch_op.drop_index("ix_materials_name")
        batch_op.drop_constraint(
            batch_op.f("fk_materials_updated_by_user_id_users"), type_="foreignkey"
        )
        batch_op.drop_column("updated_by_user_id")
        batch_op.drop_column("updated_at_utc")
        batch_op.drop_column("source_category_no")

    with op.batch_alter_table("material_tag_print_events", schema=None) as batch_op:
        batch_op.drop_index("ix_material_tag_print_events_tag")
        batch_op.drop_index("ix_material_tag_print_events_requester")
        batch_op.drop_index("ix_material_tag_print_events_batch")

    op.drop_table("material_tag_print_events")
    op.drop_table("material_tags")
    op.drop_table("material_tag_drafts")
    with op.batch_alter_table("material_tag_batches", schema=None) as batch_op:
        batch_op.drop_index("ix_material_tag_batches_purchase_order")
        batch_op.drop_index("ix_material_tag_batches_material_receiving")
        batch_op.drop_index("ix_material_tag_batches_issued_by")
        batch_op.drop_index("ix_material_tag_batches_delivery_invoice")
        batch_op.drop_index("ix_material_tag_batches_code_vendor_lot")

    op.drop_table("material_tag_batches")
    op.drop_table("material_import_rows")
    with op.batch_alter_table("material_import_batches", schema=None) as batch_op:
        batch_op.drop_index("ix_material_import_batches_file_sha256")

    op.drop_table("material_import_batches")
    # ### end Alembic commands ###
